### post new data

POST http://localhost:6000/ingest HTTP/1.1
content-type: application/json

[
    {
        "param_name": "current",
        "param_units": "A",
        "param_value": 60
    },
    {
        "param_name": "temperature",
        "param_units": "C",
        "param_value": 90
    }
]

### get processing results (alerts only)

GET http://localhost:6001/alerts HTTP/1.1
auth: very-secure-token




### manager

POST http://localhost:5002/update HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url":"http://file_server:5001/download-update/app-update.zip", 
    "target": "app", 
    "digest": "73d00cd5220a7b850ee79f7870834efd1495f81ca3e3c1865cbc875a34d833f5", 
    "digest_alg": "sha256"
}


### get update digest
GET http://localhost:5001/get-digest/app-update.zip HTTP/1.1

### get archived update file
GET http://localhost:5001/download-update/app-update.zip HTTP/1.1


### faker test: modify payload

POST http://localhost:6100/mode HTTP/1.1
content-type: application/json

{
    "fake_services": ["data_processor"],
    "active_modifiers": ["modify_payload"]
}


### faker: get supported modes
GET http://localhost:6100/modes HTTP/1.1
