@startuml "Hacked-manager3"
title Негативный сценарий: Storage подменяет файл после проверки

actor "Пользователь" as u
participant Downloader
participant Manager 
participant Storage #red
participant Verifier
participant Updater



u -> Manager: старт процесса
Manager -> Downloader++: чтение данных
Downloader --> Manager--
Manager -> Storage++: запись данных
Storage --> Manager--
Manager -> Verifier++: команда на проверку данных
Verifier -> Storage--: чтение данных
activate Storage
Storage --> Verifier--
activate Verifier
Verifier -> Verifier: проверка
Verifier --> Manager--
Manager -> Manager: анализ результатов проверки
Storage -[#red]> Storage: изменение файла
Manager -> Updater++: команда на обновление прошивки
Updater -> Storage: чтение данных
deactivate Updater
activate Storage
Storage --> Updater
deactivate Storage
activate Updater
Updater -> Updater: обновление

@enduml